name: update
on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: 2 * * * *
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: 检出
        uses: actions/checkout@v4
      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # 指定 Node.js 版本

      - name: 安装依赖（如有）
        run: npm install

      - name: 运行 JS 脚本
        run: node fetchURLByAndroid720p.js
        
      - name: 检测文件是否更新
        id: check_updates
        run: | 
          CHANGES=0
          UPDATED_FILES=$(git status --porcelain)
          if [ -n "$UPDATED_FILES" ]; then
            echo "UPDATED_FILES: $UPDATED_FILES"
            CHANGES=1
          else
            echo "No updated files. Skipping git add."          
          fi
          echo "CHANGES=$CHANGES" >> $GITHUB_ENV
      - name: 提交更改
        if: ${{ env.CHANGES!= 0 }}
        run: |    
           echo "CHANGES: ${{ env.CHANGES }}"
           git pull origin main
           git config --local user.email "474628725@qq.com"
           git config --local user.name "badboy518714"
           git add .
           git commit -m "由github actions推送更新,日期:`date`"
      - name: 推送更改
        if: ${{ env.CHANGES!= 0 }}
        run: |
           # 替换远程仓库地址，嵌入PAT完成鉴权
           git remote set-url origin https://badboy518714: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@github.com/badboy518714/migu_video.git
           # 推送（--force 可选，测试阶段用，稳定后可去掉）
           git push origin main --force
